name: agora_uikit
description: Flutter plugin to simply integrate Agora Video Calling or Live
  Video Streaming to your app with just a few lines of code.
version: 1.3.7
publish_to: none
homepage: https://www.agora.io/en/
repository: https://github.com/AgoraIO-Community/VideoUIKit-Flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  agora_rtc_engine:
    git: https://github.com/kumsumit/agora_rtc_engine.git
  agora_rtm:
    git: https://github.com/kumsumit/agora_rtm.git
  flutter:
    sdk: flutter
  http: ">=0.13.1 <2.0.0"
  permission_handler:
    git: https://github.com/kumsumit/permission_handler.git

dev_dependencies:
  flutter_lints:
    git: https://github.com/kumsumit/flutter_lints.git
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agora_uikit
        pluginClass: AgoraUikitPlugin
      ios:
        pluginClass: AgoraUikitPlugin

analyzer:
  strong-mode: true
  errors:
    mixin_inherits_from_not_object: ignore
